### ISSUE TITLE
Need to update examples and instructions

### ISSUE THREAD

**Issue by buteomont** [Redstoned/esp32_tone#1]
Thanks for the library, it's good to have for creating tones on the ESP32.
However, there are some problems in the README file and in the examples.

In the README file:
`They work just as the Arduino functions tone and noTone. For them to work You have to call setCompatibleMode(true) or setCompatibleMode() first (e.g. in setup()).`
This doesn't work, and I can't find the associated calls in your code.

Also, the examples you provide don't work.  One of them is just an empty shell!

**Comment by Redstoned** [comment]
I'm not updating this library anymore. Feel free to fork, develop further and publish this library.
